version: '3.7'

services:
  sut:
    image: postman/newman:ubuntu
    volumes:
      - type: bind
        source: ./newman
        target: /etc/newman
    entrypoint: ["/etc/newman/wait-for-kong.sh", "kong:8001"]
    command: ["run", "kong-plugin-opa.integration_tests.postman_collection.json", "-e", "docker.postman_environment.json"]
    depends_on:
      - kong

  kong-migrations:
    build: .
    command: ["kong", "migrations", "bootstrap"]
    depends_on:
      - db
    environment:
      KONG_DATABASE: postgres
      KONG_PG_DATABASE: kong
      KONG_PG_HOST: db
      KONG_PG_PASSWORD: kong
      KONG_PG_USER: kong
    restart: on-failure

  kong:
    build: .
    depends_on:
      - kong-migrations
      - opa
      - httpbin
    environment:
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: '0.0.0.0:8001'
      KONG_DATABASE: postgres
      KONG_LOG_LEVEL: debug
      KONG_PG_DATABASE: kong
      KONG_PG_HOST: db
      KONG_PG_PASSWORD: kong
      KONG_PG_USER: kong
      # add kong-plugin-opa to the list of plugins that come bundled with Kong
      KONG_PLUGINS: bundled,opa
    ports:
      - "8000-8001:8000-8001/tcp"
      - "8443:8443/tcp"
      - "127.0.0.1:8444:8444/tcp"
    restart: on-failure

  db:
    image: postgres:9.5
    environment:
      POSTGRES_DB: kong
      POSTGRES_PASSWORD: kong
      POSTGRES_USER: kong

  opa:
    image: openpolicyagent/opa:latest
    working_dir: /bundle
    command: "run --server --bundle . --log-level debug --log-format text"
    volumes:
      # load opa bundle with policy for tests 
      - type: bind
        source: ./opa/bundle
        target: /bundle
    ports:
      - "8181:8181"
  
  # mock upstream service
  httpbin:
    image: kennethreitz/httpbin
